swagger: "2.0"
info:
  version: 1.0.0
  title: "pre-esame"
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: salty-oasis-45641.herokuapp.com
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /assignments:
    get:
      description: |
        Returns all assignments from the system that the user has access to
      operationId: findAssegnments
      responses:
        200:
          description: assignment response
          schema:
            type: array
            items:
              $ref: '#/definitions/Assignment'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new assignment.  Duplicates are allowed
      operationId: addAssignment
      parameters:
        - name: new assignment
          in: body
          description: Assignment to add to the db
          required: true
          schema:
            $ref: '#/definitions/NewAssignment'
      responses:
        200:
          description: assignment response
          schema:
            $ref: '#/definitions/Assignment'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /assignments/{Assignment_ID}:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      operationId: find assignment by id
      parameters:
        - name: Assignment_ID
          in: path
          description: ID of pet to fetch
          required: true
          type: string
      responses:
        200:
          description: pet response
          schema:
            $ref: '#/definitions/Assignment'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single pet based on the ID supplied
      operationId: deletePet
      parameters:
        - name: Assignment_ID
          in: path
          description: ID of pet to delete
          required: true
          type: string
      responses:
        204:
          description: pet deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      description: modify a single assignment based on the ID
      operationId: modifyAssignment
      parameters:
        - name: Assignment_ID
          in: path
          description: ID of assignment to modify
          required: true
          type: string
        - name: assignment
          in: body
          description: Assignment to modify
          required: false
          schema:
            $ref: '#/definitions/Assignment'
      responses:
        200:
          description: assignment response
          schema:
            $ref: '#/definitions/Assignment'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Assignment:
    allOf:
      - $ref: '#/definitions/NewAssignment'
      - required:
        - Assignment_Content
        - Assignment_Type
        properties:
          Assignment_Content:
            type: string
          Assignment_Type:
            type: string
  NewAssignment:
    required:
      - Assignment_ID
      - Student_ID
    properties:
      Assignment_ID:
        type: string
      Student_ID:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string